apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: sail-operator
    app.kubernetes.io/created-by: servicemeshoperator2
    app.kubernetes.io/instance: servicemesh-operator2
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: servicemeshoperator2
    control-plane: servicemesh-operator2
  name: servicemesh-operator2-metrics-service
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: servicemesh-operator2
status:
  loadBalancer: {}
