apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: allow-chunked-length-1.22{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
  {{- if .Values.meshConfig.rootNamespace }}
  namespace: {{ .Values.meshConfig.rootNamespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    istio.io/rev: {{ .Values.revision | default "default" }}
    release: {{ .Release.Name }}
spec:
  configPatches:
    - applyTo: CLUSTER
      match:
        context: ANY
        proxy:
          proxyVersion: '^1\.22.*'
      patch:
        operation: MERGE
        value:
          http_protocol_options:
            allow_chunked_length: true
