apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: asm-mesh-default-{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
  {{- if .Values.meshConfig.rootNamespace }}
  namespace: {{ .Values.meshConfig.rootNamespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        # match clause left off matches all istio metrics, client and server
        - tagOverrides:
            mesh_id:
              value: node.metadata['MESH_ID']
            request_method:
              value: request.method
        - match:
            metric: REQUEST_COUNT
          tagOverrides:
            request_operation:
              value: istio_operation
            request_operation_path:
              value: istio_operation_path
        - match:
            metric: REQUEST_DURATION
          tagOverrides:
            request_operation:
              value: istio_operation
            request_operation_path:
              value: istio_operation_path
  tracing:
    - customTags:
        clusterID:
          environment:
            name: ISTIO_META_CLUSTER_ID
        msname:
          environment:
            name: ASM_MS_NAME
            defaultValue: unknown
        # 容器名称
        container_name:
          literal:
            value: istio-proxy
        # pod 名称
        pod_name:
          environment:
            name: POD_NAME
            defaultValue: unknown
        # 命名空间
        pod_ns:
          environment:
            name: POD_NAMESPACE
            defaultValue: unknown
      providers:
        - name: "zipkin"
