name: servicemesh-operator2
deployment:
  name: servicemesh-operator2
  annotations:
    images.v1_26_2.ztunnel: gcr.io/istio-release/ztunnel:1.26.2
    images.v1_26_2.istiod: gcr.io/istio-release/pilot:1.26.2
    images.v1_26_2.proxy: gcr.io/istio-release/proxyv2:1.26.2
    images.v1_26_2.cni: gcr.io/istio-release/install-cni:1.26.2
    images.v1_26_0.ztunnel: gcr.io/istio-release/ztunnel:1.26.0
    images.v1_26_0.istiod: gcr.io/istio-release/pilot:1.26.0
    images.v1_26_0.proxy: gcr.io/istio-release/proxyv2:1.26.0
    images.v1_26_0.cni: gcr.io/istio-release/install-cni:1.26.0
    images.v1_25_3.ztunnel: gcr.io/istio-release/ztunnel:1.25.3
    images.v1_25_3.istiod: gcr.io/istio-release/pilot:1.25.3
    images.v1_25_3.proxy: gcr.io/istio-release/proxyv2:1.25.3
    images.v1_25_3.cni: gcr.io/istio-release/install-cni:1.25.3
    images.v1_25_2.ztunnel: gcr.io/istio-release/ztunnel:1.25.2
    images.v1_25_2.istiod: gcr.io/istio-release/pilot:1.25.2
    images.v1_25_2.proxy: gcr.io/istio-release/proxyv2:1.25.2
    images.v1_25_2.cni: gcr.io/istio-release/install-cni:1.25.2
    images.v1_25_1.ztunnel: gcr.io/istio-release/ztunnel:1.25.1
    images.v1_25_1.istiod: gcr.io/istio-release/pilot:1.25.1
    images.v1_25_1.proxy: gcr.io/istio-release/proxyv2:1.25.1
    images.v1_25_1.cni: gcr.io/istio-release/install-cni:1.25.1
    images.v1_24_6.ztunnel: gcr.io/istio-release/ztunnel:1.24.6
    images.v1_24_6.istiod: gcr.io/istio-release/pilot:1.24.6
    images.v1_24_6.proxy: gcr.io/istio-release/proxyv2:1.24.6
    images.v1_24_6.cni: gcr.io/istio-release/install-cni:1.24.6
    images.v1_24_5.ztunnel: gcr.io/istio-release/ztunnel:1.24.5
    images.v1_24_5.istiod: gcr.io/istio-release/pilot:1.24.5
    images.v1_24_5.proxy: gcr.io/istio-release/proxyv2:1.24.5
    images.v1_24_5.cni: gcr.io/istio-release/install-cni:1.24.5
    images.v1_24_4.ztunnel: gcr.io/istio-release/ztunnel:1.24.4
    images.v1_24_4.istiod: gcr.io/istio-release/pilot:1.24.4
    images.v1_24_4.proxy: gcr.io/istio-release/proxyv2:1.24.4
    images.v1_24_4.cni: gcr.io/istio-release/install-cni:1.24.4
    images.v1_24_3.ztunnel: gcr.io/istio-release/ztunnel:1.24.3
    images.v1_24_3.istiod: gcr.io/istio-release/pilot:1.24.3
    images.v1_24_3.proxy: gcr.io/istio-release/proxyv2:1.24.3
    images.v1_24_3.cni: gcr.io/istio-release/install-cni:1.24.3
    images.v1_24_2.ztunnel: gcr.io/istio-release/ztunnel:1.24.2
    images.v1_24_2.istiod: gcr.io/istio-release/pilot:1.24.2
    images.v1_24_2.proxy: gcr.io/istio-release/proxyv2:1.24.2
    images.v1_24_2.cni: gcr.io/istio-release/install-cni:1.24.2
    images.v1_24_1.ztunnel: gcr.io/istio-release/ztunnel:1.24.1
    images.v1_24_1.istiod: gcr.io/istio-release/pilot:1.24.1
    images.v1_24_1.proxy: gcr.io/istio-release/proxyv2:1.24.1
    images.v1_24_1.cni: gcr.io/istio-release/install-cni:1.24.1
    images.v1_24_0.ztunnel: gcr.io/istio-release/ztunnel:1.24.0
    images.v1_24_0.istiod: gcr.io/istio-release/pilot:1.24.0
    images.v1_24_0.proxy: gcr.io/istio-release/proxyv2:1.24.0
    images.v1_24_0.cni: gcr.io/istio-release/install-cni:1.24.0
    images.v1_28-alpha_8a5e40a4.ztunnel: gcr.io/istio-testing/ztunnel:1.28-alpha.8a5e40a462e220ff2e481847f52cb69835accd20
    images.v1_28-alpha_8a5e40a4.istiod: gcr.io/istio-testing/pilot:1.28-alpha.8a5e40a462e220ff2e481847f52cb69835accd20
    images.v1_28-alpha_8a5e40a4.proxy: gcr.io/istio-testing/proxyv2:1.28-alpha.8a5e40a462e220ff2e481847f52cb69835accd20
    images.v1_28-alpha_8a5e40a4.cni: gcr.io/istio-testing/install-cni:1.28-alpha.8a5e40a462e220ff2e481847f52cb69835accd20
# NB(timonwong) Please note that the service account name should be the same as the deployment
serviceAccountName: servicemesh-operator2
csv:
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.arm64: supported
    operatorframework.io/arch.s390x: ~
    operatorframework.io/arch.ppc64le: ~
  annotations:
    provider: '{"zh":"平台", "en": "platform"}'
    provider-type: platform
    support: Alauda
    "operatorframework.io/suggested-namespace": sail-operator
    features.operators.openshift.io/cnf: ~
    features.operators.openshift.io/cni: ~
    features.operators.openshift.io/csi: ~
    features.operators.openshift.io/disconnected: ~
    features.operators.openshift.io/fips-compliant: ~
    features.operators.openshift.io/proxy-aware: ~
    features.operators.openshift.io/tls-profiles: ~
    features.operators.openshift.io/token-auth-aws: ~
    features.operators.openshift.io/token-auth-azure: ~
    features.operators.openshift.io/token-auth-gcp: ~
  displayName: Alauda Service Mesh v2
  categories: Integration & Delivery, Networking, Security
  capabilities: Seamless Upgrades
  description: Alauda Service Mesh v2 enables you to install, configure, and manage an instance of Alauda Service Mesh. Alauda Service Mesh is based on the open source Istio project.
  provider:
    name: Alauda
  icon:
    base64data: PHN2ZyB2aWV3Qm94PSIwIDAgMTAyNCAxMDI0IiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogICAgPCEtLSA8cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJyZ2IoMCwgMTIyLCAyNDUpIi8+IC0tPgogICAgPHBhdGggZD0iTTM5My41MjMyIDUxLjJMMTkwLjkwNzczMyA0MjEuNzM0NGwtMjEuODQ1MzMzIDM5LjUyNjRhMTA0Ljk3NzA2NyAxMDQuOTc3MDY3IDAgMCAwLTIuMTY3NDY3IDk3LjMzMTJsMi4xNjc0NjcgNC4xNDcyIDEyOC4xMzY1MzMgMjMxLjU5NDY2N2ExMDIuMDU4NjY3IDEwMi4wNTg2NjcgMCAwIDAgODQuOTA2NjY3IDUyLjgzODRsNC4yNDk2IDAuMDg1MzMzaDI1MS4yODk2YTEwMS45MjIxMzMgMTAxLjkyMjEzMyAwIDAgMCA4Ni45ODg4LTQ5LjIyMDI2N2wyLjE2NzQ2Ny0zLjcyMDUzMyAxMjguMTM2NTMzLTIzMS41Nzc2YTEwNC45NzcwNjcgMTA0Ljk3NzA2NyAwIDAgMCAyLjE2NzQ2Ny05Ny4zMzEybC0yLjE2NzQ2Ny00LjE0NzItMTI4LjEzNjUzMy0yMzEuNTk0NjY3YTEwMS45OTA0IDEwMS45OTA0IDAgMCAwLTg5LjE1NjI2Ny01Mi45MjM3MzNIMzkwLjQ1MTJMNDYwLjk4NzczMyA1MS4yaDI0Ni4xMTg0YTEwMS45OTA0IDEwMS45OTA0IDAgMCAxIDg5LjE1NjI2NyA1Mi45NDA4bDE5Ny41OTc4NjcgMzU3LjEyYTEwNC45NiAxMDQuOTYgMCAwIDEgMCAxMDEuNDc4NEw3OTYuMjYyNCA5MTkuODU5MkExMDEuOTkwNCAxMDEuOTkwNCAwIDAgMSA3MDcuMTA2MTMzIDk3Mi44SDMxNi44OTM4NjdhMTAxLjk5MDQgMTAxLjk5MDQgMCAwIDEtODkuMTU2MjY3LTUyLjk0MDhMMzAuMTM5NzMzIDU2Mi43MzkyYTEwNC45NiAxMDQuOTYgMCAwIDEgMC0xMDEuNDc4NEwyMjcuNzM3NiAxMDQuMTQwOEExMDEuOTkwNCAxMDEuOTkwNCAwIDAgMSAzMTYuODkzODY3IDUxLjJoNzYuNjI5MzMzek02MjEuNzM4NjY3IDI3My4wNjY2NjdjMTIuNzY1ODY3IDAgMjQuNTA3NzMzIDcuMTg1MDY3IDMwLjU0OTMzMyAxOC43MjIxMzNsMTExLjU4MTg2NyAyMTIuNjUwNjY3YTM2LjQzNzMzMyAzNi40MzczMzMgMCAwIDEtMC42MTQ0IDM0Ljg4NDI2NmwtMTEwLjc0NTYgMTkzLjk5NjhBMzQuNTQyOTMzIDM0LjU0MjkzMyAwIDAgMSA2MjIuNTU3ODY3IDc1MC45MzMzMzNoLTc4LjU3NDkzNEw0MzAuOTMzMzMzIDUzOS4xNzAxMzNhMzYuNDM3MzMzIDM2LjQzNzMzMyAwIDAgMSAwLTM0LjIxODY2Nkw1NTQuNjY2NjY3IDI3My4wNjY2NjdoNjcuMDcyeiIgZmlsbD0icmdiKDAsIDEyMiwgMjQ1KSI+PC9wYXRoPgogICAgPHBhdGggZD0iTTM4Ny40MTMzMzMgMjczLjA2NjY2N2wxMDcuNTIgMC45NzI4YTUyLjczNiA1Mi43MzYgMCAwIDAtNi42MDQ4IDguOTc3MDY2bC0xLjgyNjEzMyAzLjM3OTItMTA0LjQ4MjEzMyAyMTAuNjUzODY3YTU5LjU3OTczMyA1OS41Nzk3MzMgMCAwIDAtMi4wMzA5MzQgNDcuNjUwMTMzbDEuMzgyNCAzLjI0MjY2N0w0NzUuNDQzMiA3NTAuOTMzMzMzbC05NC42MDA1MzMtMC44ODc0NjZjLTExLjYwNTMzMy0wLjEwMjQtMjIuMjM3ODY3LTcuMzA0NTMzLTI3Ljc1MDQtMTguNzczMzM0bC05My4yNjkzMzQtMTk0LjA5OTJhMzkuNjk3MDY3IDM5LjY5NzA2NyAwIDAgMS0wLjEzNjUzMy0zMy42ODk2bDk5LjMyOC0yMTEuMzUzNmM1LjU0NjY2Ny0xMS44MTAxMzMgMTYuNTAzNDY3LTE5LjE2NTg2NyAyOC4zOTg5MzMtMTkuMDYzNDY2eiIgZmlsbD0icmdiKDEwMiwgMTc1LCAyNDkpIj48L3BhdGg+Cjwvc3ZnPgo=
    mediatype: image/svg+xml
  longDescription: |-
    Alauda Service Mesh is a platform that provides behavioral insight and operational control over a service mesh, providing a uniform way to connect, secure, and monitor microservice applications.
# setting this to true will add resources required to generate the bundle using operator-sdk
bundleGeneration: true
